window.ZenithForms = (() => {
  const services = [["emprestimo-cartao","Empréstimo imediato por cartão de crédito"],["seguro-vida","Seguro de Vida"],["seguro-residencial","Seguro residencial"],["seguro-automovel","Seguro de automóveis"],["credito-consignado","Crédito Consignado para aposentados e pensionistas"],["credito-trabalhador","Crédito do Trabalhador"],["credito-pessoal","Crédito Pessoal"],["financiamento-veiculos","Financiamento de veículos leves e pesados"],["financiamento-imoveis","Financiamento de imóveis residenciais e comerciais"],["financiamento-construcao","Financiamento para construção"],["consorcio-automoveis","Consórcio de automóveis"],["consorcio-imobiliario","Consórcio imobiliário"],["consorcio-educacao-viagens","Consórcio para educação e viagens"],["consorcio-estetica-procedimentos","Consórcio para estética e procedimentos cirúrgicos"]];
  const digits = value => value.replace(/\D/g, "");
  const mask = (value, type) => { const d = digits(value); if(type === "cpf") return d.slice(0,11).replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2"); if(type === "phone") return d.slice(0,11).replace(/(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d)/,"$1-$2"); if(type === "cep") return d.slice(0,8).replace(/(\d{5})(\d)/,"$1-$2"); return value; };
  const validCPF = value => { const d=digits(value); if(!/^\d{11}$/.test(d)||/^([0-9])\1+$/.test(d))return false; let s=0; for(let i=0;i<9;i++)s+=+d[i]*(10-i); let x=(s*10)%11; if(x===10)x=0; if(x!==+d[9])return false; s=0;for(let i=0;i<10;i++)s+=+d[i]*(11-i);x=(s*10)%11;if(x===10)x=0;return x===+d[10]; };
  const init = () => { const form=document.querySelector("[data-pf-form]"); if(!form)return; let step=1; const steps=[...form.querySelectorAll("[data-step]")]; const setStep=n=>{step=n;steps.forEach(x=>x.hidden=+x.dataset.step!==step);form.querySelectorAll(".form-stepper li").forEach((x,i)=>x.classList.toggle("is-current",i===step-1));form.querySelector("[data-form-back]").hidden=step===1;form.querySelector("[data-form-next]").hidden=step===4;form.querySelector("[data-form-submit]").hidden=step!==4;if(step===4) review();};
    const options=form.querySelector("[data-service-options]"); options.innerHTML=services.map(([id,label])=>`<label class="service-option"><input type="checkbox" name="servicos" value="${id}"><span>${label}</span></label>`).join("");
    const count=()=>{const n=form.querySelectorAll('[name="servicos"]:checked').length;form.querySelector(".selection-count").textContent=`${n} serviço${n===1?"":"s"} selecionado${n===1?"":"s"}`;};options.addEventListener("change",count);
    [["pf-cpf","cpf"],["pf-phone","phone"],["pf-cep","cep"]].forEach(([id,type])=>document.getElementById(id)?.addEventListener("input",e=>e.target.value=mask(e.target.value,type)));
    document.getElementById("pf-income")?.addEventListener("input",e=>{const n=digits(e.target.value);e.target.value=n?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(+n/100):"";});
    const error=(el,msg)=>{const group=el.closest(".form-group, .choice-group")||el.parentElement;group.querySelector(".field-error").textContent=msg;el.setAttribute("aria-invalid","true");}; const clear=el=>{const group=el.closest(".form-group, .choice-group")||el.parentElement;const out=group.querySelector(".field-error");if(out)out.textContent="";el.removeAttribute("aria-invalid");};
    const validate=()=>{const current=steps[step-1];let first;current.querySelectorAll("input[required],select[required]").forEach(el=>{clear(el);let msg="";if(el.type==="radio"){if(!current.querySelector(`[name="${el.name}"]:checked`))msg="Selecione uma opção.";}else if(!el.value)msg="Este campo é obrigatório.";else if(el.id==="pf-cpf"&&!validCPF(el.value))msg="Digite um CPF válido.";else if(el.id==="pf-phone"&&digits(el.value).length!==11)msg="Informe seu telefone com DDD.";else if(el.id==="pf-cep"&&digits(el.value).length!==8)msg="Informe seu CEP.";else if(el.type==="email"&&!el.validity.valid)msg="Digite um e-mail válido.";else if(el.type==="date"&&new Date(el.value)>new Date())msg="Informe uma data de nascimento válida.";if(msg){error(el,msg);first??=el;}});if(first){first.focus();return false;}return true;};
    const review=()=>{const data=new FormData(form);const labels={nomeCompleto:"Nome",cpf:"CPF",dataNascimento:"Data de nascimento",sexo:"Sexo",estadoCivil:"Estado civil",telefone:"Telefone",email:"E-mail",cep:"CEP",rua:"Rua",numero:"N°",cidade:"Cidade",estado:"Estado",profissao:"Profissão",rendaMensal:"Renda mensal"};const dataRows=Object.entries(labels).map(([k,l])=>`<div><span>${l}</span><strong>${data.get(k)||"—"}</strong></div>`).join("");const chosen=services.filter(([id])=>data.getAll("servicos").includes(id)).map(([,l])=>l).join(" • ")||"Nenhum serviço selecionado";form.querySelector("[data-form-review]").innerHTML=`${dataRows}<div class="form-review__services"><span>Serviços de interesse</span><strong>${chosen}</strong></div>`;};
    form.addEventListener("input",event=>clear(event.target));form.querySelector("[data-form-next]").addEventListener("click",()=>{if(validate())setStep(step+1);});form.querySelector("[data-form-back]").addEventListener("click",()=>setStep(step-1));form.addEventListener("submit",e=>{e.preventDefault();if(!validate())return;form.querySelectorAll(".form-step,.form-stepper,.form-actions").forEach(x=>x.hidden=true);form.querySelector(".form-success").hidden=false;});form.querySelector("[data-form-submit]").textContent=window.ZENITH_FORM_CONFIG?.pfSubmitLabel||"ENVIAR MEU CADASTRO"; };
  const initPJ=()=>{const f=document.querySelector('[data-pj-form]');if(!f)return;const a=['Empréstimo imediato por cartão de crédito','Seguro de Vida','Seguro residencial','Seguro de automóveis','Seguro empresarial','Crédito Pessoal','Financiamento de veículos leves e pesados','Financiamento de imóveis residenciais e comerciais','Financiamento para construção','Consórcio de automóveis','Consórcio imobiliário','Consórcio para educação e viagens','Consórcio para estética e procedimentos cirúrgicos'];let n=1,s=[...f.querySelectorAll('[data-pj-step]')],go=x=>{n=x;s.forEach(e=>e.hidden=+e.dataset.pjStep!==n);f.querySelectorAll('.form-stepper li').forEach((e,i)=>e.classList.toggle('is-current',i===n-1));f.querySelector('[data-pj-back]').hidden=n===1;f.querySelector('[data-pj-next]').hidden=n===5;f.querySelector('[data-pj-submit]').hidden=n!==5;};let b=f.querySelector('[data-pj-services]');b.innerHTML=a.map((x,i)=>`<label class="service-option"><input type="checkbox" name="pjServices" value="pj-${i}"><span>${x}</span></label>`).join('');b.onchange=()=>{let c=f.querySelectorAll('[name="pjServices"]:checked').length;f.querySelector('.selection-count').textContent=`${c} serviço${c===1?'':'s'} selecionado${c===1?'':'s'}`};let ok=()=>{let q=[...s[n-1].querySelectorAll('[required]')].find(e=>e.type==='radio'?!f.querySelector(`[name="${e.name}"]:checked`):!e.value);if(q){q.focus();q.setAttribute('aria-invalid','true');return false}return true};f.querySelector('[data-pj-next]').onclick=()=>{if(ok())go(n+1)};f.querySelector('[data-pj-back]').onclick=()=>go(n-1);f.querySelector('[data-pj-submit]').textContent=window.ZENITH_FORM_CONFIG?.pjSubmitLabel||'ENVIAR CADASTRO DA EMPRESA';f.onsubmit=e=>{e.preventDefault();f.querySelectorAll('.form-step,.form-stepper,.form-actions').forEach(x=>x.hidden=true);f.querySelector('.form-success').hidden=false}};
  const initMictmr=()=>{const f=document.querySelector('[data-mictmr-form]');if(!f)return;let n=1,s=[...f.querySelectorAll('[data-mf-step]')],go=x=>{n=x;s.forEach(e=>e.hidden=+e.dataset.mfStep!==n);f.querySelectorAll('.form-stepper li').forEach((e,i)=>e.classList.toggle('is-current',i===n-1));f.querySelector('[data-mf-back]').hidden=n===1;f.querySelector('[data-mf-next]').hidden=n===3;f.querySelector('[data-mf-submit]').hidden=n!==3;if(n===3){let d=new FormData(f);f.querySelector('[data-mf-review]').innerHTML=['perfil','nome','cpf','telefone','email'].map(k=>`<div><span>${k}</span><strong>${d.get(k)||'—'}</strong></div>`).join('')}};f.querySelector('[data-mf-next]').onclick=()=>{let bad=[...s[n-1].querySelectorAll('[required]')].find(e=>e.type==='radio'?!f.querySelector('[name="perfil"]:checked'):!e.value);if(bad){bad.focus();return}go(n+1)};f.querySelector('[data-mf-back]').onclick=()=>go(n-1);f.onsubmit=e=>{e.preventDefault();f.querySelectorAll('[data-mf-step],.form-stepper,.form-actions').forEach(x=>x.hidden=true);f.querySelector('.form-success').hidden=false}};
  return {init,initPJ,initMictmr};
})();
